use crate::img::ARR as imgArr;

pub fn colors() {
    let vga_buffer = 0xb8000 as *mut u8;
    for color in 0..16 {
        for row in 0..25 {
            for col_offset in 0..5 {
                let index = (row * 80 + (color * 5 + col_offset)) * 2;
                unsafe {
                    *vga_buffer.add(index + 1) = (color as u8) << 4;
                    *vga_buffer.add(index) = b' ';
                }
            }
        }
    }
}

pub fn image() {
    let vga_buffer = 0xb8000 as *mut u8;
    // img::ARR is the [u8; 2000] generated by Python
    for (i, &color_attr) in imgArr.iter().enumerate() {
        unsafe {
            *vga_buffer.add(i * 2) = b' ';         // Character
            *vga_buffer.add(i * 2 + 1) = color_attr; // Background Color Attribute
        }
    }
}